# Generated by Django 3.0.6 on 2020-07-10 01:29

from django.db import migrations
from sportsreference.mlb.roster import Roster, Player

def add_pitchers(apps, schema_editor):
    Player = apps.get_model('core', 'Player')
    braves = Roster('ATL', '1995')
    pitchers = [player for player in braves.players if player.position == 'P']

    for player in Player.objects.all():
        player.name = pitcher.name
        player.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_player'),
    ]

    operations = [
        migrations.RunPython(add_pitchers),
    ]
