# Generated by Django 3.0.6 on 2020-07-11 17:09

from django.db import migrations
from sportsreference.mlb.roster import Roster, Player

def add_pitchers(apps, schema_editor):
    Player = apps.get_model('core', 'Player')
    braves = Roster('ATL', '1995')
    pitchers = [player for player in braves.players if player.position == 'P']
    summary_list = []

    for pitcher in pitchers:
        summary_list.append((pitcher.name))

    summary=tuple(summary_list)

    Player.objects.bulk_create(Player(name=name) for name in summary)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200711_1301'),
    ]

    operations = [
        migrations.RunPython(add_pitchers)
    ]
