# Generated by Django 3.0.6 on 2020-07-12 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200711_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='games',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
