# Generated by Django 3.0.6 on 2020-07-19 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200712_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='era',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='player',
            name='whip',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='player',
            name='wins',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
