# Generated by Django 3.0.6 on 2020-07-19 10:22

from django.db import migrations
from sportsreference.mlb.roster import Roster, Player

def add_pitchers(apps, schema_editor):
    Player = apps.get_model('core', 'Player')
    summary_list = []
    
    braves = Roster('ATL', '1996')
    pitchers = [player for player in braves.players if player.position == 'P']
    for pitcher in pitchers:
        summary_list.append((pitcher.name, '2015', pitcher.position, pitcher('2015').games, pitcher('2015').era, pitcher('2015').wins, pitcher('2015').whip))
    
    summary = tuple(summary_list)

    Player.objects.bulk_create(Player(name=name, season=season, position=position, games=games, era=era, wins=wins, whip=whip) for name, season, position, games, era, wins, whip in summary)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200718_2136'),
    ]

    operations = [
        migrations.RunPython(add_pitchers)
    ]
