# Generated by Django 3.0.6 on 2020-07-19 11:55

from django.db import migrations
from sportsreference.mlb.roster import Roster, Player

def add_pitchers(apps, schema_editor):
    Player = apps.get_model('core', 'Player')
    summary_list = []
    
    for x in range(1980, 1990):
        season = str(x)
        braves = Roster('ATL', season)
        pitchers = [player for player in braves.players if player.position == 'P']
        for pitcher in pitchers:
            summary_list.append((pitcher.name, season, pitcher.position, pitcher(season).games, pitcher(season).era, pitcher(season).wins, pitcher(season).whip))
        
        summary = tuple(summary_list)

        Player.objects.bulk_create(Player(name=name, season=season, position=position, games=games, era=era, wins=wins, whip=whip) for name, season, position, games, era, wins, whip in summary)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200719_0622'),
    ]

    operations = [
        migrations.RunPython(add_pitchers)
    ]
