# Generated by Django 3.0.6 on 2020-07-21 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Year',
        ),
    ]
